
# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: night
# MathJax
mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  per_page: true

# LangSelect
langselect:
  enable: true
  options:
    en: English
    zh-CN: 简体中文
